from sqlalchemy import Column, Integer, String, Boolean, Numeric, DateTime, Text
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Produit(Base):
    __tablename__ = "produit_temp"

    id = Column(Integer, primary_key=True, autoincrement=True)
    nom = Column(String(400), nullable=True)
    nomEN = Column(String(400), nullable=True)
    nomInitial = Column(String(400), nullable=True)
    description = Column(String(2000), nullable=True)
    typeProduit = Column(Integer, nullable=True, default=30)
    vendable = Column(Boolean, nullable=False, default=0)
    idFournisseur = Column(Integer, nullable=True, default=778)
    prixAppel = Column(Numeric(18, 3), nullable=True)
    prixAppelAchat = Column(String(30), nullable=True)
    tauxTVA = Column(Numeric(18, 3), nullable=True)
    referenceExterne = Column(String(30), nullable=True)
    minAgeEnfant1 = Column(Integer, nullable=True)
    maxAgeEnfant1 = Column(Integer, nullable=True)
    minAgeEnfant2 = Column(Integer, nullable=True)
    maxAgeEnfant2 = Column(Integer, nullable=True)
    nbJour = Column(Integer, nullable=True)
    nbNuit = Column(Integer, nullable=True)
    dureeHeure = Column(Integer, nullable=True)
    dureeMinute = Column(Integer, nullable=True)
    adresse = Column(String(400), nullable=True)
    gestionStock = Column(Integer, nullable=True)
    devise = Column(Integer, nullable=True, default=403)
    pension = Column(Integer, nullable=True)
    actif = Column(Boolean, nullable=True, default=1)
    categorie = Column(Integer, nullable=True)
    jourOperation = Column(String(7), nullable=True)
    dateDebut = Column(Integer, nullable=True)
    dateFin = Column(Integer, nullable=True)
    heureDebut = Column(Integer, nullable=True)
    heureFin = Column(Integer, nullable=True)
    dateDebutVente = Column(Integer, nullable=True)
    dateFinVente = Column(Integer, nullable=True)
    typeProduitCeto = Column(Integer, nullable=True)
    typeRepasCeto = Column(Integer, nullable=True)
    dateCreation = Column(DateTime, nullable=True)
    dateModification = Column(DateTime, nullable=True)
    prixMini = Column(Numeric(18, 3), nullable=True)
    prixMaxi = Column(Numeric(18, 3), nullable=True)
    urlResa = Column(String(100), nullable=True)
    urlTableauPrix = Column(String(100), nullable=True)
    enPromo = Column(Boolean, nullable=True)
    dispos = Column(Boolean, nullable=True)
    vol = Column(Boolean, nullable=True, default=1)
    classeVol = Column(Integer, nullable=True)
    produitExterne = Column(Boolean, nullable=True)
    typeForfait = Column(Integer, nullable=True)
    codeComptable = Column(String(100), nullable=True)
    codePostal = Column(String(30), nullable=True)
    produitOuvertATousLesClients = Column(Boolean, nullable=True, default=1)
    groupe = Column(Integer, nullable=True, default=279)
    groupe2 = Column(Integer, nullable=True)
    interditAuxBebes = Column(Boolean, nullable=True)
    interditAuxEnfants = Column(Boolean, nullable=True)
    engagementSurStock = Column(Integer, nullable=True)
    xmlCeto = Column(Text, nullable=True)
    typePrestation = Column(Integer, nullable=True, default=449)
    heureRDV = Column(Integer, nullable=True)
    lieuRDV = Column(String(30), nullable=True)
    longitude = Column(String(30), nullable=True)
    latitude = Column(String(30), nullable=True)
    idVille = Column(Integer, nullable=True)
    idLocaliteDepart = Column(Integer, nullable=True)
    idLocaliteArrivee = Column(Integer, nullable=True)
    idTypeService = Column(Integer, nullable=True)
    idGammeService = Column(Integer, nullable=True)
    idTypeVehicule = Column(Integer, nullable=True)
    idTypeTrajet = Column(Integer, nullable=True)
    trajetSimple = Column(Boolean, nullable=False, default=1)
    organisateur = Column(String(100), nullable=True)
    niveauTraduction = Column(String(30), nullable=True)
    niveauTraductionExterne = Column(String(30), nullable=True)
    codePopularite = Column(String(30), nullable=True)
    ProductType = Column(String(1000), nullable=True)
    ProductGroup = Column(String(100), nullable=True)
    ProductCategory = Column(String(100), nullable=True)
    ProductSubCategory = Column(String(100), nullable=True)
    referencesExternesQuestions = Column(String(2000), nullable=True)
    dateModificationProduit = Column(DateTime, nullable=True)
    ContentSequence = Column(String(30), nullable=True)
    suspendu = Column(Boolean, nullable=False, default=0)
    delaiAnnulationSansFrais = Column(Integer, nullable=True, default=999)
    idOrganisateur = Column(Integer, nullable=True, default=778)
    b2c = Column(Boolean, nullable=False, default=1)
    commentaire = Column(String(2000), nullable=True)
    typePrestationInitial = Column(Integer, nullable=True)
    codeQualification = Column(String(100), nullable=True)
    valide = Column(Boolean, nullable=False, default=0)
    idTypeBillet = Column(Integer, nullable=True)
    emissionVoucherImmediate = Column(Boolean, nullable=False, default=0)
    nomPT = Column(String(400), nullable=True)
    idResponsable = Column(Integer, nullable=True)
    idTcms = Column(Integer, nullable=True)
    tauxMargeSupplementairePrixClientFinal = Column(Integer, nullable=False, default=1) # Why 1
    prive = Column(Boolean, nullable=True)
    sousTypePrestation = Column(Integer, nullable=True)
    codeImportanceVente = Column(String(30), nullable=True)
    dateMiseAjourDescription = Column(DateTime, nullable=True)
    dateMiseAjourTarif = Column(DateTime, nullable=True)
    idOdoo = Column(Integer, nullable=True)
    envoiVoucher = Column(Integer, nullable=True)
    allowCustomTravelerPickup = Column(Boolean, nullable=True)
    cancelIfBadWeather = Column(Boolean, nullable=False, default=0)
    cancelIfInsufficientTravelers = Column(Boolean, nullable=False, default=0)
    unite = Column(Integer, nullable=True, default=63)
    adulteMax = Column(Integer, nullable=True)
    adulteMin = Column(Integer, nullable=True)
